<?php
if(isset($_POST['signup']))
{
$uname=$_POST['username'];
$email=$_POST['email'];
$pwd=$_POST['password'];
$fname=$_POST['firstName'];
$lname=$_POST['lastName'];
$gender=$_POST['gender'];
$bday=$_POST['birthday'];
$bio=$_POST['bio'];
$pno=$_POST['phoneNumber'];
$city=$_POST['city'];
$street=$_POST['street'];
$db=mysql_connect("localhost","root","");
mysql_select_db("ostore",$db);
$query="INSERT INTO `ostore`.`users` (`User_Name`, `Email`, `Password`, `First_Name`,`Last_Name`, `Gender`,`Birthday`,`Bio`,`Phone_Number`,`City`,`Street`) VALUES('$uname','$email','$pwd','$fname','$lname','$gender','$bday','$bio','$pno','$city','$street')";
$re=mysql_query($query,$db);
if($re){
echo"Successfull";
header("location:signup.php");
}
else
echo"failed";
}
?>